name: Deploy to Firebase
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pnpm i && pnpm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANDREAMANGIONE_E1426 }}'
          channelId: live
          projectId: andreamangione-e1426
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
